
#option(HAVE_CONFIG_H "use a config file" ON)

option(_SRC_STATETRACKER_CONFIG_H "_SRC_STATETRACKER_CONFIG_H" ON)

option(STATE_TRACKER_DEBUG "STATE_TRACKER_DEBUG" OFF)

option(STATE_TRACKER_HAVE_BOOST "STATE_TRACKER_HAVE_BOOST" ON)

option(STATE_TRACKER_HAVE_DLFCN_H "STATE_TRACKER_HAVE_DLFCN_H" ON)

option(STATE_TRACKER_HAVE_EXECINFO_H "STATE_TRACKER_HAVE_EXECINFO_H" ON)

option(STATE_TRACKER_HAVE_INTTYPES_H "STATE_TRACKER_HAVE_INTTYPES_H" ON)

option(STATE_TRACKER_HAVE_MEMORY_H "STATE_TRACKER_HAVE_MEMORY_H" ON)

option(STATE_TRACKER_HAVE_MPI "STATE_TRACKER_HAVE_MPI" ON)

option(STATE_TRACKER_HAVE_PTHREAD_H "STATE_TRACKER_HAVE_PTHREAD_H" ON)

option(STATE_TRACKER_HAVE_STDINT_H "STATE_TRACKER_HAVE_STDINT_H" ON)

option(STATE_TRACKER_HAVE_STDIO_H "STATE_TRACKER_HAVE_STDIO_H" ON)

option(STATE_TRACKER_HAVE_STDLIB_H "STATE_TRACKER_HAVE_STDLIB_H" ON)

option(STATE_TRACKER_HAVE_STRINGS_H "STATE_TRACKER_HAVE_STRINGS_H" ON)

option(STATE_TRACKER_HAVE_STRING_H "STATE_TRACKER_HAVE_STRING_H" ON)

option(STATE_TRACKER_HAVE_SYS_STAT_H "STATE_TRACKER_HAVE_SYS_STAT_H" ON)

option(STATE_TRACKER_HAVE_SYS_TYPES_H "STATE_TRACKER_HAVE_SYS_TYPES_H" ON)

option(STATE_TRACKER_HAVE_UNISTD_H "STATE_TRACKER_HAVE_UNISTD_H" ON)

option(STATE_TRACKER_LT_OBJDIR "STATE_TRACKER_LT_OBJDIR" ON)

option(STATE_TRACKER_PACKAGE "STATE_TRACKER_PACKAGE" ON)

option(STATE_TRACKER_PACKAGE_BUGREPORT "STATE_TRACKER_PACKAGE_BUGREPORT" ON)

option(STATE_TRACKER_PACKAGE_NAME "STATE_TRACKER_PACKAGE_NAME" ON)

option(STATE_TRACKER_PACKAGE_STRING "STATE_TRACKER_PACKAGE_STRING" ON)

option(STATE_TRACKER_PACKAGE_TARNAME "STATE_TRACKER_PACKAGE_TARNAME" ON)

option(STATE_TRACKER_PACKAGE_VERSION "STATE_TRACKER_PACKAGE_VERSION" ON)

option(STATE_TRACKER_STDC_HEADERS "STATE_TRACKER_STDC_HEADERS" ON)

option(STATE_TRACKER_VERSION "STATE_TRACKER_VERSION" ON)

option(STATE_TRACKER_WITH_CALLPATH "STATE_TRACKER_WITH_CALLPATH" OFF)

